### ISSUE TITLE
When will this be available? 

### ISSUE THREAD

**Issue by CheyenneForbes** [quasarframework/app-extension-feathersjs#1]

**Comment by nothingismagick** [comment]
Hi! Thanks for your early interest. I hope to have an alpha ready to look
at sometime this week. I'll reply here to keep you updated.

**Comment by CheyenneForbes** [comment]
Would be great if it could be npm/yarn built as a "mode" like electron, cordova, etc.

**Comment by CheyenneForbes** [comment]
Should've asked this before my previous question, will this be an integration for feathersjs client or server?

**Comment by nothingismagick** [comment]
Both, but full of options

**Comment by CheyenneForbes** [comment]
any update? 👀

**Comment by nothingismagick** [comment]
Sry - lost this from my radar - too many things going on. Feel free to help out and let us know what could be better to make this work for you!

**Comment by nothingismagick** [comment]
It's available to try out now:
```
$ quasar ext add @quasar/feathersjs
```

**Comment by CheyenneForbes** [comment]
Hey quick question, this allows quasar UI and feathers API to be served from the same host and port right?

**Comment by CheyenneForbes** [comment]
@nothingismagick has development on this stopped?
